version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - $HOME/docker/valheim/config:/config
      - $HOME/docker/valheim/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/docker/valheim/valheim.env
    restart: always
    stop_grace_period: 2m
